version: "2"
services:
  apache:
    image: eeacms/apache:2.4-1.0
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
    - varnish
    environment:
      SERVER_ADMIN: "helpdesk@climate-adapt-test.eea.europa.eu"
      SERVER_NAME: "climate-adapt-test.eea.europa.eu"
      RewriteRule: "^/(.*) http://varnish/VirtualHostBase/http/climate-adapt-test.eea.europa.eu:80/cca/VirtualHostRoot/$$1 [P,L]"
      TZ: "Europe/Copenhagen"
  varnish:
    build: varnish/
    # image: eeacms/varnish
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
    - haproxy
    environment:
      BACKENDS: "haproxy"
      BACKENDS_PROBE_INTERVAL: "3s"
      BACKENDS_PROBE_TIMEOUT: "1s"
      BACKENDS_PROBE_WINDOW: "3"
      BACKENDS_PROBE_THRESHOLD: "2"
      BACKENDS_PORT: "5000"
      DNS_ENABLED: "true"
      TZ: "Europe/Copenhagen"
  haproxy:
    image: eeacms/haproxy:1.7-1.0
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
    - plone
    ports:
    - "80:5000"
    - "1936:1936"
    environment:
      BACKENDS: "plone"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "True"
      TZ: "Europe/Copenhagen"
  plone:
    image: eeacms/eea.docker.
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
    - zeoserver
    - memcached
    environment:
      ZOPE_MODE: "zeo_client"
      TZ: "Europe/Copenhagen"
    volumes:
    - cca-downloads:/data/downloads
    - cca-plone-data:/data
  async:
    image: eeacms/eea.docker.
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
    - zeoserver
    - memcached
    environment:
     ZOPE_MODE: "zeo_async"
     TZ: "Europe/Copenhagen"
    volumes:
    - cca-downloads:/data/downloads
    - cca-async-data:/data
  memcached:
    image: memcached:1.4.35
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
    command:
    - "-m"
    - "2048"
  zeoserver:
    image: plone:4.3.10
    labels:
      io.rancher.scheduler.affinity:host_label: hostname=
    environment:
      TZ: "Europe/Copenhagen"
    command:
    - zeoserver
    volumes:
    - cca-data:/data
  rsync-server:
    image: eeacms/rsync
    labels:
      io.rancher.scheduler.affinity:host_label: hostname=
    command:
    - server
    ports:
    - "22"
    volumes:
    - cca-data:/data
    environment:
      SSH_AUTH_KEY_1:

volumes:
  cca-plone-data:
    per_container: true
  cca-async-data:
    per_container: true
  cca-data:
    driver: rancher-nfs
  cca-downloads:
driver: rancher-nfs
