version: '2'
services:
  apache:
    scale: 1
    upgrade_strategy:
      start_first: true
    health_check:
      port: 80
      interval: 30000
      initializing_timeout: 300000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 3000
  varnish:
    scale: 1
    upgrade_strategy:
      start_first: true
    health_check:
      port: 80
      interval: 30000
      initializing_timeout: 300000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 3000
  haproxy:
    scale: 1
    upgrade_strategy:
      start_first: true
    health_check:
      port: 4242
      interval: 30000
      initializing_timeout: 300000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 3000
  memcached:
    scale: 1
    upgrade_strategy:
      start_first: true
    health_check:
      port: 11211
      interval: 30000
      initializing_timeout: 300000
      unhealthy_threshold: 3
      strategy: recreate
      response_timeout: 3000
      healthy_threshold: 2
  plone:
    scale: 12
    upgrade_strategy:
      start_first: true
    health_check:
      port: 8080
      interval: 30000
      initializing_timeout: 300000
      unhealthy_threshold: 3
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      response_timeout: 6000
      healthy_threshold: 2
  async:
    scale: 1
    upgrade_strategy:
      start_first: true
    health_check:
      port: 8080
      interval: 30000
      initializing_timeout: 300000
      unhealthy_threshold: 3
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      response_timeout: 6000
      healthy_threshold: 2
  zeoserver:
    scale: 1
    health_check:
      port: 8100
      interval: 30000
      initializing_timeout: 300000
      unhealthy_threshold: 3
      strategy: recreate
      response_timeout: 6000
      healthy_threshold: 2
  cron-zeopack:
    scale: 1
  cron-get-broken-links:
    scale: 1
  cron-archive-news:
    scale: 1
  cron-send-mayoradapt-reminders:
    scale: 1
