haproxy:
  scale: 1
  health_check:
    port: 4242
    interval: 30000
    initializing_timeout: 90000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 3000
memcached:
  scale: 1
  health_check:
    port: 11211
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 3000
    healthy_threshold: 2
postfix:
  scale: 1
  health_check:
    port: 25
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 3000
    healthy_threshold: 2
plone:
  scale: ${PLONE_SCALE}
  health_check:
    port: 8080
    interval: 5000
    initializing_timeout: 600000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 6000
    healthy_threshold: 2
async:
  scale: ${ASYNC_SCALE}
  health_check:
    port: 8080
    interval: 5000
    initializing_timeout: 600000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 6000
    healthy_threshold: 2
zeoserver:
  scale: 1
  health_check:
    port: 8100
    interval: 5000
    initializing_timeout: 600000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 6000
    healthy_threshold: 2
data:
  scale: 1
